# JunkedOut funding configuration
# The project is currently fully founder-funded.
# No corporate sponsorship, political funding, or external donors.
# Public funding channels may be introduced in the future under documented governance rules.
